logging:
  level:
    # log eureka client
    org.springframework.cloud.gateway: INFO
    com.etna.gpe.mycloseshop: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: ${MS_LOGIN_HOST:http://localhost}:${MS_LOGIN_PORT:8081}${MS_LOGIN_PATH:/api/ms-login-api/}
          #uri: lb://MS-LOGIN-API/api/ms-login-api
          predicates:
            - Path=/api/ms-login-api/**
          filters:
            - name: CircuitBreaker
              args:
                name: login-service
                fallbackUri: forward:/fallback/login

        - id: shop-service
          uri: ${MS_SHOP_HOST:http://localhost}:${MS_SHOP_PORT:8082}${MS_SHOP_PATH:/api/ms-shop-api/}
          #uri: lb://MS-SHOP-API/api/ms-shop-api
          predicates:
              - Path=/api/ms-shop-api/**
          filters:
              - name: CircuitBreaker
                args:
                    name: shop-service
                    fallbackUri: forward:/fallback/shop

        - id: quote-service
          uri: ${MS_QUOTE_HOST:http://localhost}:${MS_QUOTE_PORT:8082}${MS_QUOTE_PATH:/api/ms-quote-api/}
          #uri: lb://MS-QUOTE-API/api/ms-quote-api
          predicates:
            - Path=/api/ms-quote-api/**
          filters:
            - name: CircuitBreaker
              args:
                name: quote-service
                fallbackUri: forward:/fallback/quote

        - id: payment-service
          uri: ${MS_PAYMENT_HOST:http://localhost}:${MS_PAYMENT_PORT:8082}${MS_PAYMENT_PATH:/api/ms-payment-api/}
          #uri: lb://MS-PAYMENT-API/api/ms-payment-api
          predicates:
            - Path=/api/ms-payment-api/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackUri: forward:/fallback/payment

        - id: social-service
          uri: ${MS_SOCIAL_HOST:http://localhost}:${MS_SOCIAL_PORT:8082}${MS_SOCIAL_PATH:/api/ms-social-api/}
          #uri: lb://MS-SOCIAL-API/api/ms-social-api
          predicates:
            - Path=/api/ms-social-api/**
          filters:
            - name: CircuitBreaker
              args:
                name: social-service
                fallbackUri: forward:/fallback/social

      default-filters:
        - name: RemoveRequestHeader
          args:
            name: X-Forwarded-For
        - name: RemoveRequestHeader
          args:
            name: X-Forwarded-Proto
        - name: RemoveRequestHeader
          args:
            name: X-Forwarded-Port
        - name: RemoveRequestHeader
          args:
            name: Forwarded

server:
  port: 8080
  max-http-request-header-size: 16384
